+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Dec 29 11:05:31 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL vdo
+ pkgs=vdo
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs vdo --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 11:23:59 ago on Wed Dec 28 23:42:05 2022.
Error: 
 Problem: conflicting requests
  - nothing provides kmod-kvdo >= 6.2 needed by vdo-6.2.0.298-14.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 11:23:59 ago on Wed Dec 28 23:42:05 2022.
Error: 
 Problem: conflicting requests
  - nothing provides kmod-kvdo >= 6.2 needed by vdo-6.2.0.298-14.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Dec 29 11:06:06 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Dec 29 11:06:06 2022 - INFO  - Start testing...
+ test_execution vdo.service
+ service=vdo.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-29 11:06:06'
+ test_restart vdo.service
+ service=vdo.service
+ systemctl restart vdo.service
Failed to restart vdo.service: Unit vdo.service not found.
+ CHECK_RESULT 5 0 0 'vdo.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='vdo.service restart failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'vdo.service restart failed'
+ LOG_ERROR 'vdo.service restart failed'
+ message='vdo.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vdo.service restart failed'
Thu Dec 29 11:06:07 2022 - ERROR - vdo.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Dec 29 11:06:08 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: active'
+ systemctl status vdo.service
Unit vdo.service could not be found.
+ CHECK_RESULT 1 0 0 'vdo.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vdo.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vdo.service restart failed'
+ LOG_ERROR 'vdo.service restart failed'
+ message='vdo.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vdo.service restart failed'
Thu Dec 29 11:06:14 2022 - ERROR - vdo.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Dec 29 11:06:15 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop vdo.service
Failed to stop vdo.service: Unit vdo.service not loaded.
+ CHECK_RESULT 5 0 0 'vdo.service stop failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='vdo.service stop failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'vdo.service stop failed'
+ LOG_ERROR 'vdo.service stop failed'
+ message='vdo.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vdo.service stop failed'
Thu Dec 29 11:06:16 2022 - ERROR - vdo.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Thu Dec 29 11:06:16 2022 - ERROR - ../common/common_lib.sh line 39
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: inactive'
+ systemctl status vdo.service
Unit vdo.service could not be found.
+ CHECK_RESULT 1 0 0 'vdo.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vdo.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vdo.service stop failed'
+ LOG_ERROR 'vdo.service stop failed'
+ message='vdo.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vdo.service stop failed'
Thu Dec 29 11:06:23 2022 - ERROR - vdo.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Dec 29 11:06:24 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start vdo.service
Failed to start vdo.service: Unit vdo.service not found.
+ CHECK_RESULT 5 0 0 'vdo.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='vdo.service start failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'vdo.service start failed'
+ LOG_ERROR 'vdo.service start failed'
+ message='vdo.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vdo.service start failed'
Thu Dec 29 11:06:24 2022 - ERROR - vdo.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Dec 29 11:06:25 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status vdo.service
+ grep 'Active: active'
Unit vdo.service could not be found.
+ CHECK_RESULT 1 0 0 'vdo.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vdo.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vdo.service start failed'
+ LOG_ERROR 'vdo.service start failed'
+ message='vdo.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vdo.service start failed'
Thu Dec 29 11:06:31 2022 - ERROR - vdo.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Dec 29 11:06:32 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled vdo.service
+ service=vdo.service
++ systemctl is-enabled vdo.service
Failed to get unit file state for vdo.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Thu Dec 29 11:06:33 2022 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2022-12-29 11:06:06' -u vdo.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of vdo.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of vdo.service'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_reload vdo.service
+ service=vdo.service
+ systemctl start vdo.service
Failed to start vdo.service: Unit vdo.service not found.
+ systemctl reload vdo.service
+ grep 'Job type reload is not applicable'
+ CHECK_RESULT 1 0 0 'Job type reload is not applicable for unit vdo.service'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit vdo.service'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Job type reload is not applicable for unit vdo.service'
+ LOG_ERROR 'Job type reload is not applicable for unit vdo.service'
+ message='Job type reload is not applicable for unit vdo.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Job type reload is not applicable for unit vdo.service'
Thu Dec 29 11:06:34 2022 - ERROR - Job type reload is not applicable for unit vdo.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 91'
+ message='../common/common_lib.sh line 91'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 91'
Thu Dec 29 11:06:34 2022 - ERROR - ../common/common_lib.sh line 91
+ return 0
+ systemctl status vdo.service
+ grep 'Active: active'
Unit vdo.service could not be found.
+ systemctl status vdo.service
+ grep 'inactive (dead)'
Unit vdo.service could not be found.
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Dec 29 11:06:35 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 11:06:36 2022 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Dec 29 11:06:36 2022 - INFO  - start environment cleanup.
+ systemctl stop vdo.service
Failed to stop vdo.service: Unit vdo.service not loaded.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 11:23:59 ago on Wed Dec 28 23:42:05 2022.
Error: 
 Problem: conflicting requests
  - nothing provides kmod-kvdo >= 6.2 needed by vdo-6.2.0.298-14.oe2203.riscv64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 11:23:59 ago on Wed Dec 28 23:42:05 2022.
Error: 
 Problem: conflicting requests
  - nothing provides kmod-kvdo >= 6.2 needed by vdo-6.2.0.298-14.oe2203.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 11:23:59 ago on Wed Dec 28 23:42:05 2022.\nError: \n Problem: conflicting requests\n  - nothing provides kmod-kvdo >= 6.2 needed by vdo-6.2.0.298-14.oe2203.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Dec 29 11:06:39 2022 - INFO  - Finish environment cleanup!
