+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Dec 29 09:05:21 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL sanlk-reset
+ pkgs=sanlk-reset
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs sanlk-reset --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpw6iir4z7
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpw6iir4z7
+ service=sanlk-resetd.service
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Dec 29 09:06:13 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Dec 29 09:06:14 2022 - INFO  - Start testing...
+ test_execution sanlk-resetd.service
+ service=sanlk-resetd.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-29 09:06:14'
+ test_restart sanlk-resetd.service
+ service=sanlk-resetd.service
+ systemctl restart sanlk-resetd.service
A dependency job for sanlk-resetd.service failed. See 'journalctl -xe' for details.
+ CHECK_RESULT 1 0 0 'sanlk-resetd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'sanlk-resetd.service restart failed'
+ LOG_ERROR 'sanlk-resetd.service restart failed'
+ message='sanlk-resetd.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'sanlk-resetd.service restart failed'
Thu Dec 29 09:06:15 2022 - ERROR - sanlk-resetd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Dec 29 09:06:15 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status sanlk-resetd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'sanlk-resetd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'sanlk-resetd.service restart failed'
+ LOG_ERROR 'sanlk-resetd.service restart failed'
+ message='sanlk-resetd.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'sanlk-resetd.service restart failed'
Thu Dec 29 09:06:22 2022 - ERROR - sanlk-resetd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Dec 29 09:06:23 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop sanlk-resetd.service
+ CHECK_RESULT 0 0 0 'sanlk-resetd.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status sanlk-resetd.service
+ grep 'Active: inactive'
     Active: inactive (dead)
+ CHECK_RESULT 0 0 0 'sanlk-resetd.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl start sanlk-resetd.service
A dependency job for sanlk-resetd.service failed. See 'journalctl -xe' for details.
+ CHECK_RESULT 1 0 0 'sanlk-resetd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'sanlk-resetd.service start failed'
+ LOG_ERROR 'sanlk-resetd.service start failed'
+ message='sanlk-resetd.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'sanlk-resetd.service start failed'
Thu Dec 29 09:06:30 2022 - ERROR - sanlk-resetd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Dec 29 09:06:30 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status sanlk-resetd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'sanlk-resetd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'sanlk-resetd.service start failed'
+ LOG_ERROR 'sanlk-resetd.service start failed'
+ message='sanlk-resetd.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'sanlk-resetd.service start failed'
Thu Dec 29 09:06:37 2022 - ERROR - sanlk-resetd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Dec 29 09:06:37 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled sanlk-resetd.service
+ service=sanlk-resetd.service
++ systemctl is-enabled sanlk-resetd.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable sanlk-resetd.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/sanlk-resetd.service
+ find /etc/systemd/system/multi-user.target.wants/sanlk-resetd.service
/etc/systemd/system/multi-user.target.wants/sanlk-resetd.service
+ CHECK_RESULT 0 0 0 'sanlk-resetd.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable sanlk-resetd.service
Removed /etc/systemd/system/multi-user.target.wants/sanlk-resetd.service.
+ find /etc/systemd/system/multi-user.target.wants/sanlk-resetd.service
find: ‘/etc/systemd/system/multi-user.target.wants/sanlk-resetd.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'sanlk-resetd.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='sanlk-resetd.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2022-12-29 09:06:14' -u sanlk-resetd.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Dec 29 09:06:14 openEuler-riscv64 systemd[1]: Dependency failed for daemon for host reset.
Dec 29 09:06:14 openEuler-riscv64 systemd[1]: sanlk-resetd.service: Job sanlk-resetd.service/start failed with result 'dependency'.
Dec 29 09:06:29 openEuler-riscv64 systemd[1]: Dependency failed for daemon for host reset.
Dec 29 09:06:29 openEuler-riscv64 systemd[1]: sanlk-resetd.service: Job sanlk-resetd.service/start failed with result 'dependency'.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of sanlk-resetd.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of sanlk-resetd.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of sanlk-resetd.service'
+ LOG_ERROR 'There is an error message for the log of sanlk-resetd.service'
+ message='There is an error message for the log of sanlk-resetd.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of sanlk-resetd.service'
Thu Dec 29 09:06:47 2022 - ERROR - There is an error message for the log of sanlk-resetd.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Thu Dec 29 09:06:47 2022 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ test_reload sanlk-resetd.service
+ service=sanlk-resetd.service
+ systemctl start sanlk-resetd.service
A dependency job for sanlk-resetd.service failed. See 'journalctl -xe' for details.
+ systemctl reload sanlk-resetd.service
+ grep 'Job type reload is not applicable'
Failed to reload sanlk-resetd.service: Job type reload is not applicable for unit sanlk-resetd.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit sanlk-resetd.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit sanlk-resetd.service'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status sanlk-resetd.service
+ grep 'Active: active'
+ systemctl status sanlk-resetd.service
+ grep 'inactive (dead)'
     Active: inactive (dead)
+ systemctl status sanlk-resetd.service
+ grep 'Condition check'
+ grep skip
+ CHECK_RESULT 1 0 0 'sanlk-resetd.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='sanlk-resetd.service reload causes the service status to change'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'sanlk-resetd.service reload causes the service status to change'
+ LOG_ERROR 'sanlk-resetd.service reload causes the service status to change'
+ message='sanlk-resetd.service reload causes the service status to change'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'sanlk-resetd.service reload causes the service status to change'
Thu Dec 29 09:06:49 2022 - ERROR - sanlk-resetd.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 95'
+ message='../common/common_lib.sh line 95'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 95'
Thu Dec 29 09:06:50 2022 - ERROR - ../common/common_lib.sh line 95
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Dec 29 09:06:51 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 09:06:51 2022 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Dec 29 09:06:52 2022 - INFO  - start environment cleanup.
+ systemctl stop sanlk-resetd.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpw6iir4z7 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpw6iir4z7
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Dec 29 09:07:08 2022 - INFO  - Finish environment cleanup!
