+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start to config params of the case.'
+ message='Start to config params of the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to config params of the case.'
Thu Feb  2 22:42:51 2023 - INFO  - Start to config params of the case.
+ table_name=sec015
+ chain_name=sec015_chain
+ nft add table inet sec015
oe_test_nftables_listen_package.sh: line 27: nft: command not found
+ nft add chain inet sec015 sec015_chain '{' type filter hook input priority 0 ';' '}'
oe_test_nftables_listen_package.sh: line 28: nft: command not found
+ LOG_INFO 'End to config params of the case.'
+ message='End to config params of the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to config params of the case.'
Thu Feb  2 22:42:51 2023 - INFO  - End to config params of the case.
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Thu Feb  2 22:42:52 2023 - INFO  - Start executing testcase.
+ nft add rule inet sec015 sec015_chain udp dport 22 accept
oe_test_nftables_listen_package.sh: line 34: nft: command not found
+ nft --handle list chain inet sec015 sec015_chain
oe_test_nftables_listen_package.sh: line 35: nft: command not found
+ grep sec015_chain
+ CHECK_RESULT 1 0 0 'exec '\''nft add rule inet sec015 sec015_chain udp dport 22 accept'\'' failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='exec '\''nft add rule inet sec015 sec015_chain udp dport 22 accept'\'' failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'exec '\''nft add rule inet sec015 sec015_chain udp dport 22 accept'\'' failed'
+ LOG_ERROR 'exec '\''nft add rule inet sec015 sec015_chain udp dport 22 accept'\'' failed'
+ message='exec '\''nft add rule inet sec015 sec015_chain udp dport 22 accept'\'' failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'exec '\''nft add rule inet sec015 sec015_chain udp dport 22 accept'\'' failed'
Thu Feb  2 22:42:53 2023 - ERROR - exec 'nft add rule inet sec015 sec015_chain udp dport 22 accept' failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nftables_listen_package.sh line 36'
+ message='oe_test_nftables_listen_package.sh line 36'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_nftables_listen_package.sh line 36'
Thu Feb  2 22:42:53 2023 - ERROR - oe_test_nftables_listen_package.sh line 36
+ return 0
++ nft --handle list chain inet sec015 sec015_chain
++ grep udp
oe_test_nftables_listen_package.sh: line 37: nft: command not found
++ awk -F ' ' '{printf $NF}'
+ handle_num=
+ nft replace rule inet sec015 sec015_chain handle tcp dport 22 meta nftrace set 1 accept
oe_test_nftables_listen_package.sh: line 38: nft: command not found
+ nft --handle list chain inet sec015 sec015_chain
oe_test_nftables_listen_package.sh: line 39: nft: command not found
+ grep 'tcp dport 22 meta nftrace set 1 accept'
+ CHECK_RESULT 1 0 0 'exec '\''nft replace'\'' failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='exec '\''nft replace'\'' failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'exec '\''nft replace'\'' failed'
+ LOG_ERROR 'exec '\''nft replace'\'' failed'
+ message='exec '\''nft replace'\'' failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'exec '\''nft replace'\'' failed'
Thu Feb  2 22:42:54 2023 - ERROR - exec 'nft replace' failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nftables_listen_package.sh line 40'
+ message='oe_test_nftables_listen_package.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_nftables_listen_package.sh line 40'
Thu Feb  2 22:42:55 2023 - ERROR - oe_test_nftables_listen_package.sh line 40
+ return 0
+ pid_num=3925
+ nft monitor
+ SSH_CMD pwd 127.0.0.1 'openEuler12#$' root
oe_test_nftables_listen_package.sh: line 41: nft: command not found
+ grep 'inet sec015 sec015_chain'
+ cmd=pwd
+ remoteip=127.0.0.1
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c pwd -i 127.0.0.1 -u root -p 'openEuler12#$' -t 300 -o 22
Thu Feb  2 22:42:56 2023 - WARN  - the remote user uses the default configuration.
Thu Feb  2 22:42:56 2023 - WARN  - the remote password uses the default configuration.
Thu Feb  2 22:42:57 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@127.0.0.1 pwd
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ED25519 key fingerprint is SHA256:cXH/bDdo3zo17K2M3IcjyixQERxg4O/ZHVcK2O4KwlI.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.
root@127.0.0.1's password: 
/root
+ ret=0
+ test 0 -ne 0
+ return 0
+ SLEEP_WAIT 10
+ wait_time=10
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 10 --cmd '' --mode 1
+ kill -9 3925
oe_test_nftables_listen_package.sh: line 45: kill: (3925) - No such process
++ cat monitor_log
++ wc -l
+ '[' 0 -gt 0 ']'
+ CHECK_RESULT 1 0 0 'exec '\''nft monitor'\'' failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='exec '\''nft monitor'\'' failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'exec '\''nft monitor'\'' failed'
+ LOG_ERROR 'exec '\''nft monitor'\'' failed'
+ message='exec '\''nft monitor'\'' failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'exec '\''nft monitor'\'' failed'
Thu Feb  2 22:43:11 2023 - ERROR - exec 'nft monitor' failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nftables_listen_package.sh line 47'
+ message='oe_test_nftables_listen_package.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_nftables_listen_package.sh line 47'
Thu Feb  2 22:43:12 2023 - ERROR - oe_test_nftables_listen_package.sh line 47
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Thu Feb  2 22:43:12 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Feb  2 22:43:13 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Feb  2 22:43:14 2023 - INFO  - start environment cleanup.
+ nft delete table inet sec015
oe_test_nftables_listen_package.sh: line 53: nft: command not found
+ rm -rf monitor_log
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Feb  2 22:43:14 2023 - INFO  - Finish environment cleanup!
