+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Feb  7 12:46:54 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'cobbler httpd'
+ pkgs='cobbler httpd'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'cobbler httpd' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpakye6yk8
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpakye6yk8
+ systemctl start httpd
+ systemctl start cobblerd
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Feb  7 12:55:32 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run testcase.'
+ message='Start to run testcase.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run testcase.'
Tue Feb  7 12:55:36 2023 - INFO  - Start to run testcase.
+ cobbler image add --name=OpenEuler1
cobblerd does not appear to be running/accessible: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 852, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 503 Service Unavailable>
+ CHECK_RESULT 1 0 0 'Failed option: image add'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image add'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image add'
+ LOG_ERROR 'Failed option: image add'
+ message='Failed option: image add'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image add'
Tue Feb  7 12:56:06 2023 - ERROR - Failed option: image add
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 33'
+ message='oe_test_cobbler_image.sh line 33'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 33'
Tue Feb  7 12:56:07 2023 - ERROR - oe_test_cobbler_image.sh line 33
+ return 0
+ cobbler image copy --name=OpenEuler1 --newname=OpenEuler2
exception on server: 'internal error, unknown image name OpenEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: image copy'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: image copy'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler image list
+ grep OpenEuler2
+ CHECK_RESULT 1 0 0 'Failed option: image copy'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image copy'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image copy'
+ LOG_ERROR 'Failed option: image copy'
+ message='Failed option: image copy'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image copy'
Tue Feb  7 12:56:30 2023 - ERROR - Failed option: image copy
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 37'
+ message='oe_test_cobbler_image.sh line 37'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 37'
Tue Feb  7 12:56:31 2023 - ERROR - oe_test_cobbler_image.sh line 37
+ return 0
+ cobbler image edit --name=openEuler1 --owners=tom
exception on server: 'internal error, unknown image name openEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: image edit'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: image edit'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler image report --name=openEuler1
+ grep tom
+ CHECK_RESULT 1 0 0 'Failed option: image edit'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image edit'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image edit'
+ LOG_ERROR 'Failed option: image edit'
+ message='Failed option: image edit'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image edit'
Tue Feb  7 12:57:13 2023 - ERROR - Failed option: image edit
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 41'
+ message='oe_test_cobbler_image.sh line 41'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 41'
Tue Feb  7 12:57:16 2023 - ERROR - oe_test_cobbler_image.sh line 41
+ return 0
+ grep OpenEuler
+ cobbler image list
+ CHECK_RESULT 1 0 0 'Failed option: image list'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image list'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image list'
+ LOG_ERROR 'Failed option: image list'
+ message='Failed option: image list'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image list'
Tue Feb  7 12:58:01 2023 - ERROR - Failed option: image list
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 43'
+ message='oe_test_cobbler_image.sh line 43'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 43'
Tue Feb  7 12:58:03 2023 - ERROR - oe_test_cobbler_image.sh line 43
+ return 0
+ cobbler image find
+ grep OpenEuler
+ CHECK_RESULT 1 0 0 'Failed option: image find'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image find'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image find'
+ LOG_ERROR 'Failed option: image find'
+ message='Failed option: image find'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image find'
Tue Feb  7 12:58:41 2023 - ERROR - Failed option: image find
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 45'
+ message='oe_test_cobbler_image.sh line 45'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 45'
Tue Feb  7 12:58:46 2023 - ERROR - oe_test_cobbler_image.sh line 45
+ return 0
+ cobbler image remove --name=OpenEuler1
exception on server: 'internal error, unknown image name OpenEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: image remove'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: image remove'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler image list
+ grep OpenEuler1
+ CHECK_RESULT 1 0 1 'Failed option: image remove'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='Failed option: image remove'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ cobbler image rename --name=OpenEuler2 --newname=OpenEuler3
exception on server: 'internal error, unknown image name OpenEuler2'
+ CHECK_RESULT 0 0 0 'Failed option: image rename'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: image rename'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler image list
+ grep OpenEuler3
+ CHECK_RESULT 1 0 0 'Failed option: image rename'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image rename'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image rename'
+ LOG_ERROR 'Failed option: image rename'
+ message='Failed option: image rename'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image rename'
Tue Feb  7 13:00:44 2023 - ERROR - Failed option: image rename
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 53'
+ message='oe_test_cobbler_image.sh line 53'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 53'
Tue Feb  7 13:00:48 2023 - ERROR - oe_test_cobbler_image.sh line 53
+ return 0
+ grep Name
+ cobbler image report --name=OpenEuler3
+ CHECK_RESULT 1 0 0 'Failed option: image report'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: image report'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: image report'
+ LOG_ERROR 'Failed option: image report'
+ message='Failed option: image report'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: image report'
Tue Feb  7 13:01:21 2023 - ERROR - Failed option: image report
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_image.sh line 55'
+ message='oe_test_cobbler_image.sh line 55'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_image.sh line 55'
Tue Feb  7 13:01:24 2023 - ERROR - oe_test_cobbler_image.sh line 55
+ return 0
+ LOG_INFO 'End to run testcase.'
+ message='End to run testcase.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run testcase.'
Tue Feb  7 13:01:28 2023 - INFO  - End to run testcase.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Feb  7 13:01:32 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Feb  7 13:01:35 2023 - INFO  - Start to restore the test environment.
+ systemctl stop httpd
+ systemctl stop cobblerd
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpakye6yk8 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpakye6yk8
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Feb  7 13:06:00 2023 - INFO  - End to restore the test environment.
