+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Dec 29 08:56:43 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL samba
+ pkgs=samba
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs samba --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpnt6vq6qv
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpnt6vq6qv
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Dec 29 08:58:08 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Dec 29 08:58:09 2022 - INFO  - Start testing...
+ test_execution nmb.service
+ service=nmb.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-29 08:58:09'
+ test_restart nmb.service
+ service=nmb.service
+ systemctl restart nmb.service
Job for nmb.service failed because the control process exited with error code.
See "systemctl status nmb.service" and "journalctl -xeu nmb.service" for details.
+ CHECK_RESULT 1 0 0 'nmb.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service restart failed'
+ LOG_ERROR 'nmb.service restart failed'
+ message='nmb.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service restart failed'
Thu Dec 29 08:58:10 2022 - ERROR - nmb.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Dec 29 08:58:11 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status nmb.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'nmb.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service restart failed'
+ LOG_ERROR 'nmb.service restart failed'
+ message='nmb.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service restart failed'
Thu Dec 29 08:58:17 2022 - ERROR - nmb.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Dec 29 08:58:18 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop nmb.service
+ CHECK_RESULT 0 0 0 'nmb.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='nmb.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status nmb.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'nmb.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service stop failed'
+ LOG_ERROR 'nmb.service stop failed'
+ message='nmb.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service stop failed'
Thu Dec 29 08:58:25 2022 - ERROR - nmb.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Dec 29 08:58:25 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start nmb.service
Job for nmb.service failed because the control process exited with error code.
See "systemctl status nmb.service" and "journalctl -xeu nmb.service" for details.
+ CHECK_RESULT 1 0 0 'nmb.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service start failed'
+ LOG_ERROR 'nmb.service start failed'
+ message='nmb.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service start failed'
Thu Dec 29 08:58:26 2022 - ERROR - nmb.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Dec 29 08:58:27 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status nmb.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'nmb.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service start failed'
+ LOG_ERROR 'nmb.service start failed'
+ message='nmb.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service start failed'
Thu Dec 29 08:58:33 2022 - ERROR - nmb.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Dec 29 08:58:34 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled nmb.service
+ service=nmb.service
++ systemctl is-enabled nmb.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable nmb.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/nmb.service
+ find /etc/systemd/system/multi-user.target.wants/nmb.service
/etc/systemd/system/multi-user.target.wants/nmb.service
+ CHECK_RESULT 0 0 0 'nmb.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='nmb.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable nmb.service
Removed /etc/systemd/system/multi-user.target.wants/nmb.service.
+ find /etc/systemd/system/multi-user.target.wants/nmb.service
find: ‘/etc/systemd/system/multi-user.target.wants/nmb.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'nmb.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='nmb.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ journalctl --since '2022-12-29 08:58:09' -u nmb.service
+ grep -i 'fail\|error'
Dec 29 08:58:09 openEuler-riscv64 nmbd[764]: /usr/sbin/nmbd: error while loading shared libraries: libmessages-util-samba4.so: cannot open shared object file: No such file or directory
Dec 29 08:58:09 openEuler-riscv64 systemd[1]: nmb.service: Failed with result 'exit-code'.
Dec 29 08:58:09 openEuler-riscv64 systemd[1]: Failed to start Samba NMB Daemon.
Dec 29 08:58:25 openEuler-riscv64 nmbd[780]: /usr/sbin/nmbd: error while loading shared libraries: libmessages-util-samba4.so: cannot open shared object file: No such file or directory
Dec 29 08:58:25 openEuler-riscv64 systemd[1]: nmb.service: Failed with result 'exit-code'.
Dec 29 08:58:25 openEuler-riscv64 systemd[1]: Failed to start Samba NMB Daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of nmb.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of nmb.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of nmb.service'
+ LOG_ERROR 'There is an error message for the log of nmb.service'
+ message='There is an error message for the log of nmb.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of nmb.service'
Thu Dec 29 08:58:43 2022 - ERROR - There is an error message for the log of nmb.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Thu Dec 29 08:58:43 2022 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ systemctl start nmb.service
Job for nmb.service failed because the control process exited with error code.
See "systemctl status nmb.service" and "journalctl -xeu nmb.service" for details.
+ sed -i 's\ExecStart=/usr/sbin/nmbd\ExecStart=/usr/sbin/nmbd -D\g' /usr/lib/systemd/system/nmb.service
+ systemctl daemon-reload
+ systemctl reload nmb.service
nmb.service is not active, cannot reload.
+ CHECK_RESULT 1 0 0 'nmb.service reload failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service reload failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service reload failed'
+ LOG_ERROR 'nmb.service reload failed'
+ message='nmb.service reload failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service reload failed'
Thu Dec 29 08:58:48 2022 - ERROR - nmb.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_nmb.sh line 35'
+ message='oe_test_service_nmb.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_nmb.sh line 35'
Thu Dec 29 08:58:49 2022 - ERROR - oe_test_service_nmb.sh line 35
+ return 0
+ systemctl status nmb.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'nmb.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nmb.service reload causes the service status to change'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nmb.service reload causes the service status to change'
+ LOG_ERROR 'nmb.service reload causes the service status to change'
+ message='nmb.service reload causes the service status to change'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'nmb.service reload causes the service status to change'
Thu Dec 29 08:58:50 2022 - ERROR - nmb.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_nmb.sh line 37'
+ message='oe_test_service_nmb.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_nmb.sh line 37'
Thu Dec 29 08:58:50 2022 - ERROR - oe_test_service_nmb.sh line 37
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Dec 29 08:58:51 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 08:58:52 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Dec 29 08:58:52 2022 - INFO  - start environment cleanup.
+ sed -i 's\ExecStart=/usr/sbin/nmbd -D\ExecStart=/usr/sbin/nmbd\g' /usr/lib/systemd/system/nmb.service
+ systemctl daemon-reload
+ systemctl reload nmb.service
nmb.service is not active, cannot reload.
+ systemctl stop nmb.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpnt6vq6qv ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpnt6vq6qv
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Dec 29 08:59:26 2022 - INFO  - Finish environment cleanup!
