+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Dec 29 06:27:40 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL quota
+ pkgs=quota
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs quota --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpk_9rbk6a
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpk_9rbk6a
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Dec 29 06:28:38 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Dec 29 06:28:39 2022 - INFO  - Start testing...
+ test_execution quota_nld.service
+ service=quota_nld.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-29 06:28:39'
+ test_restart quota_nld.service
+ service=quota_nld.service
+ systemctl restart quota_nld.service
Job for quota_nld.service failed because the control process exited with error code.
See "systemctl status quota_nld.service" and "journalctl -xeu quota_nld.service" for details.
+ CHECK_RESULT 1 0 0 'quota_nld.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'quota_nld.service restart failed'
+ LOG_ERROR 'quota_nld.service restart failed'
+ message='quota_nld.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'quota_nld.service restart failed'
Thu Dec 29 06:28:40 2022 - ERROR - quota_nld.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Dec 29 06:28:41 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status quota_nld.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'quota_nld.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'quota_nld.service restart failed'
+ LOG_ERROR 'quota_nld.service restart failed'
+ message='quota_nld.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'quota_nld.service restart failed'
Thu Dec 29 06:28:47 2022 - ERROR - quota_nld.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Dec 29 06:28:48 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop quota_nld.service
+ CHECK_RESULT 0 0 0 'quota_nld.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status quota_nld.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'quota_nld.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'quota_nld.service stop failed'
+ LOG_ERROR 'quota_nld.service stop failed'
+ message='quota_nld.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'quota_nld.service stop failed'
Thu Dec 29 06:28:54 2022 - ERROR - quota_nld.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Dec 29 06:28:55 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start quota_nld.service
Job for quota_nld.service failed because the control process exited with error code.
See "systemctl status quota_nld.service" and "journalctl -xeu quota_nld.service" for details.
+ CHECK_RESULT 1 0 0 'quota_nld.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'quota_nld.service start failed'
+ LOG_ERROR 'quota_nld.service start failed'
+ message='quota_nld.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'quota_nld.service start failed'
Thu Dec 29 06:28:56 2022 - ERROR - quota_nld.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Dec 29 06:28:57 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status quota_nld.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'quota_nld.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'quota_nld.service start failed'
+ LOG_ERROR 'quota_nld.service start failed'
+ message='quota_nld.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'quota_nld.service start failed'
Thu Dec 29 06:29:03 2022 - ERROR - quota_nld.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Dec 29 06:29:04 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled quota_nld.service
+ service=quota_nld.service
++ systemctl is-enabled quota_nld.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable quota_nld.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/quota_nld.service
+ find /etc/systemd/system/multi-user.target.wants/quota_nld.service
/etc/systemd/system/multi-user.target.wants/quota_nld.service
+ CHECK_RESULT 0 0 0 'quota_nld.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='quota_nld.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable quota_nld.service
Removed /etc/systemd/system/multi-user.target.wants/quota_nld.service.
+ find /etc/systemd/system/multi-user.target.wants/quota_nld.service
find: ‘/etc/systemd/system/multi-user.target.wants/quota_nld.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'quota_nld.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='quota_nld.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2022-12-29 06:28:39' -u quota_nld.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Dec 29 06:28:39 openEuler-riscv64 systemd[1]: quota_nld.service: Failed with result 'exit-code'.
Dec 29 06:28:39 openEuler-riscv64 systemd[1]: Failed to start Disk quota netlink message daemon.
Dec 29 06:28:55 openEuler-riscv64 systemd[1]: quota_nld.service: Failed with result 'exit-code'.
Dec 29 06:28:55 openEuler-riscv64 systemd[1]: Failed to start Disk quota netlink message daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of quota_nld.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of quota_nld.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of quota_nld.service'
+ LOG_ERROR 'There is an error message for the log of quota_nld.service'
+ message='There is an error message for the log of quota_nld.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of quota_nld.service'
Thu Dec 29 06:29:12 2022 - ERROR - There is an error message for the log of quota_nld.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Thu Dec 29 06:29:13 2022 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ test_reload quota_nld.service
+ service=quota_nld.service
+ systemctl start quota_nld.service
Job for quota_nld.service failed because the control process exited with error code.
See "systemctl status quota_nld.service" and "journalctl -xeu quota_nld.service" for details.
+ systemctl reload quota_nld.service
+ grep 'Job type reload is not applicable'
Failed to reload quota_nld.service: Job type reload is not applicable for unit quota_nld.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit quota_nld.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit quota_nld.service'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status quota_nld.service
+ grep 'Active: active'
+ systemctl status quota_nld.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Dec 29 06:29:14 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 06:29:15 2022 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Dec 29 06:29:16 2022 - INFO  - start environment cleanup.
+ systemctl stop quota_nld.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpk_9rbk6a ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpk_9rbk6a
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Dec 29 06:29:33 2022 - INFO  - Finish environment cleanup!
