+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Dec 29 09:09:12 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL sanlock
+ pkgs=sanlock
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs sanlock --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpfwpqtv9b
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpfwpqtv9b
+ service=wdmd.service
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Dec 29 09:10:03 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Dec 29 09:10:03 2022 - INFO  - Start testing...
+ test_execution wdmd.service
+ service=wdmd.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-29 09:10:03'
+ test_restart wdmd.service
+ service=wdmd.service
+ systemctl restart wdmd.service
Job for wdmd.service failed because the control process exited with error code.
See "systemctl status wdmd.service" and "journalctl -xeu wdmd.service" for details.
+ CHECK_RESULT 1 0 0 'wdmd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='wdmd.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'wdmd.service restart failed'
+ LOG_ERROR 'wdmd.service restart failed'
+ message='wdmd.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'wdmd.service restart failed'
Thu Dec 29 09:10:04 2022 - ERROR - wdmd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Dec 29 09:10:05 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status wdmd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'wdmd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='wdmd.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'wdmd.service restart failed'
+ LOG_ERROR 'wdmd.service restart failed'
+ message='wdmd.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'wdmd.service restart failed'
Thu Dec 29 09:10:11 2022 - ERROR - wdmd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Dec 29 09:10:12 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop wdmd.service
+ CHECK_RESULT 0 0 0 'wdmd.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='wdmd.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status wdmd.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'wdmd.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='wdmd.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'wdmd.service stop failed'
+ LOG_ERROR 'wdmd.service stop failed'
+ message='wdmd.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'wdmd.service stop failed'
Thu Dec 29 09:10:19 2022 - ERROR - wdmd.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Dec 29 09:10:20 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start wdmd.service
Job for wdmd.service failed because the control process exited with error code.
See "systemctl status wdmd.service" and "journalctl -xeu wdmd.service" for details.
+ CHECK_RESULT 1 0 0 'wdmd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='wdmd.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'wdmd.service start failed'
+ LOG_ERROR 'wdmd.service start failed'
+ message='wdmd.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'wdmd.service start failed'
Thu Dec 29 09:10:21 2022 - ERROR - wdmd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Dec 29 09:10:22 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status wdmd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'wdmd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='wdmd.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'wdmd.service start failed'
+ LOG_ERROR 'wdmd.service start failed'
+ message='wdmd.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'wdmd.service start failed'
Thu Dec 29 09:10:28 2022 - ERROR - wdmd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Dec 29 09:10:29 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled wdmd.service
+ service=wdmd.service
++ systemctl is-enabled wdmd.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ grep 'Created symlink'
++ systemctl enable wdmd.service
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/wdmd.service
+ find /etc/systemd/system/multi-user.target.wants/wdmd.service
/etc/systemd/system/multi-user.target.wants/wdmd.service
+ CHECK_RESULT 0 0 0 'wdmd.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='wdmd.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable wdmd.service
Removed /etc/systemd/system/multi-user.target.wants/wdmd.service.
+ find /etc/systemd/system/multi-user.target.wants/wdmd.service
find: ‘/etc/systemd/system/multi-user.target.wants/wdmd.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'wdmd.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='wdmd.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2022-12-29 09:10:03' -u wdmd.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Dec 29 09:10:04 openEuler-riscv64 systemd-wdmd[1003]: /lib/systemd/systemd-wdmd: line 51: failure: command not found
Dec 29 09:10:04 openEuler-riscv64 systemd[1]: wdmd.service: Control process exited, code=exited, status=1/FAILURE
Dec 29 09:10:04 openEuler-riscv64 systemd[1]: wdmd.service: Failed with result 'exit-code'.
Dec 29 09:10:04 openEuler-riscv64 systemd[1]: Failed to start Watchdog Multiplexing Daemon.
Dec 29 09:10:20 openEuler-riscv64 systemd-wdmd[1025]: /lib/systemd/systemd-wdmd: line 51: failure: command not found
Dec 29 09:10:20 openEuler-riscv64 systemd[1]: wdmd.service: Control process exited, code=exited, status=1/FAILURE
Dec 29 09:10:20 openEuler-riscv64 systemd[1]: wdmd.service: Failed with result 'exit-code'.
Dec 29 09:10:20 openEuler-riscv64 systemd[1]: Failed to start Watchdog Multiplexing Daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of wdmd.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of wdmd.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of wdmd.service'
+ LOG_ERROR 'There is an error message for the log of wdmd.service'
+ message='There is an error message for the log of wdmd.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of wdmd.service'
Thu Dec 29 09:10:38 2022 - ERROR - There is an error message for the log of wdmd.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Thu Dec 29 09:10:39 2022 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ test_reload wdmd.service
+ service=wdmd.service
+ systemctl start wdmd.service
Job for wdmd.service failed because the control process exited with error code.
See "systemctl status wdmd.service" and "journalctl -xeu wdmd.service" for details.
+ systemctl reload wdmd.service
+ grep 'Job type reload is not applicable'
Failed to reload wdmd.service: Job type reload is not applicable for unit wdmd.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit wdmd.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit wdmd.service'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status wdmd.service
+ grep 'Active: active'
+ systemctl status wdmd.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Dec 29 09:10:40 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 09:10:41 2022 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Dec 29 09:10:41 2022 - INFO  - start environment cleanup.
+ systemctl stop wdmd.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpfwpqtv9b ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpfwpqtv9b
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Dec 29 09:10:57 2022 - INFO  - Finish environment cleanup!
