+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Feb  7 13:26:22 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'cobbler httpd'
+ pkgs='cobbler httpd'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'cobbler httpd' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmptubiw65h
+ '[' -z '' ']'
+ tmpfile=/tmp/tmptubiw65h
+ systemctl start httpd
+ systemctl start cobblerd
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Feb  7 13:34:28 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run testcase.'
+ message='Start to run testcase.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run testcase.'
Tue Feb  7 13:34:30 2023 - INFO  - Start to run testcase.
+ cobbler package add --name=OpenEuler1
cobblerd does not appear to be running/accessible: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 852, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 503 Service Unavailable>
+ CHECK_RESULT 1 0 0 'Failed option: package add'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package add'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package add'
+ LOG_ERROR 'Failed option: package add'
+ message='Failed option: package add'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package add'
Tue Feb  7 13:34:47 2023 - ERROR - Failed option: package add
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 33'
+ message='oe_test_cobbler_package.sh line 33'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 33'
Tue Feb  7 13:34:49 2023 - ERROR - oe_test_cobbler_package.sh line 33
+ return 0
+ cobbler package copy --name=OpenEuler1 --newname=OpenEuler2
exception on server: 'internal error, unknown package name OpenEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: package copy'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: package copy'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler package list
+ grep OpenEuler2
+ CHECK_RESULT 1 0 0 'Failed option: package copy'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package copy'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package copy'
+ LOG_ERROR 'Failed option: package copy'
+ message='Failed option: package copy'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package copy'
Tue Feb  7 13:35:41 2023 - ERROR - Failed option: package copy
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 37'
+ message='oe_test_cobbler_package.sh line 37'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 37'
Tue Feb  7 13:35:45 2023 - ERROR - oe_test_cobbler_package.sh line 37
+ return 0
+ cobbler package edit --name=openEuler1 --owners=tom
exception on server: 'internal error, unknown package name openEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: package edit'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: package edit'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep tom
+ cobbler package report --name=openEuler1
+ CHECK_RESULT 1 0 0 'Failed option: package edit'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package edit'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package edit'
+ LOG_ERROR 'Failed option: package edit'
+ message='Failed option: package edit'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package edit'
Tue Feb  7 13:37:02 2023 - ERROR - Failed option: package edit
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 41'
+ message='oe_test_cobbler_package.sh line 41'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 41'
Tue Feb  7 13:37:08 2023 - ERROR - oe_test_cobbler_package.sh line 41
+ return 0
+ cobbler package list
+ grep OpenEuler
+ CHECK_RESULT 1 0 0 'Failed option: package list'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package list'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package list'
+ LOG_ERROR 'Failed option: package list'
+ message='Failed option: package list'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package list'
Tue Feb  7 13:37:43 2023 - ERROR - Failed option: package list
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 43'
+ message='oe_test_cobbler_package.sh line 43'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 43'
Tue Feb  7 13:37:48 2023 - ERROR - oe_test_cobbler_package.sh line 43
+ return 0
+ cobbler package find
+ grep OpenEuler
+ CHECK_RESULT 1 0 0 'Failed option: package find'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package find'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package find'
+ LOG_ERROR 'Failed option: package find'
+ message='Failed option: package find'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package find'
Tue Feb  7 13:38:19 2023 - ERROR - Failed option: package find
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 45'
+ message='oe_test_cobbler_package.sh line 45'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 45'
Tue Feb  7 13:38:23 2023 - ERROR - oe_test_cobbler_package.sh line 45
+ return 0
+ cobbler package remove --name=OpenEuler1
exception on server: 'internal error, unknown package name OpenEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: package remove'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: package remove'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep OpenEuler1
+ cobbler package list
+ CHECK_RESULT 1 0 1 'Failed option: package remove'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='Failed option: package remove'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ cobbler package rename --name=OpenEuler2 --newname=OpenEuler3
exception on server: 'internal error, unknown package name OpenEuler2'
+ CHECK_RESULT 0 0 0 'Failed option: package rename'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: package rename'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler package list
+ grep OpenEuler3
+ CHECK_RESULT 1 0 0 'Failed option: package rename'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package rename'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package rename'
+ LOG_ERROR 'Failed option: package rename'
+ message='Failed option: package rename'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package rename'
Tue Feb  7 13:40:06 2023 - ERROR - Failed option: package rename
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 53'
+ message='oe_test_cobbler_package.sh line 53'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 53'
Tue Feb  7 13:40:10 2023 - ERROR - oe_test_cobbler_package.sh line 53
+ return 0
+ cobbler package report --name=OpenEuler3
+ grep Name
+ CHECK_RESULT 1 0 0 'Failed option: package report'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: package report'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: package report'
+ LOG_ERROR 'Failed option: package report'
+ message='Failed option: package report'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed option: package report'
Tue Feb  7 13:40:39 2023 - ERROR - Failed option: package report
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_package.sh line 55'
+ message='oe_test_cobbler_package.sh line 55'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_package.sh line 55'
Tue Feb  7 13:40:42 2023 - ERROR - oe_test_cobbler_package.sh line 55
+ return 0
+ LOG_INFO 'End to run testcase.'
+ message='End to run testcase.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run testcase.'
Tue Feb  7 13:40:45 2023 - INFO  - End to run testcase.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Feb  7 13:40:50 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Feb  7 13:40:54 2023 - INFO  - Start to restore the test environment.
+ systemctl stop httpd
+ systemctl stop cobblerd
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmptubiw65h ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmptubiw65h
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Feb  7 13:44:40 2023 - INFO  - End to restore the test environment.
